const {test}=require('node:test'),assert=require('node:assert/strict');
const {createEggScorpion,tickEggScorpion,scorpionGeometry,damageEggScorpion,scorpionDanger}=require('./egg-scorpion.js');
const arena={x:1000,y:-1000,w:1460},player=()=>({x:1650,y:-1020,vx:0,vy:0,ground:true,jumpAttack:false,hurt:0});
function until(b,state,p=player(),max=1600){for(let i=0;i<max&&b.state!==state;i++)tickEggScorpion(b,p);assert.equal(b.state,state);}
function strike(b){const g=scorpionGeometry(b);return damageEggScorpion(b,{...player(),x:g.eyes[b.hits===1?1:0].x,y:g.eyes[b.hits===1?1:0].y,ground:false,jumpAttack:true});}
test('entrance reveals armor before anchoring and releasing control',()=>{const b=createEggScorpion(arena);assert.equal(b.state,'entrance');tickEggScorpion(b,player());assert.ok(b.age<240);until(b,'idle');assert.equal(b.anchored,true);assert.equal(b.hits,0);});
test('tail attack warns and locks a ground target before live strike',()=>{const b=createEggScorpion(arena);until(b,'tail-windup');const x=b.target.x;for(let i=0;i<20;i++)tickEggScorpion(b,{...player(),x:2000});assert.equal(b.target.x,x);assert.equal(scorpionDanger(b,player()),false);until(b,'tail-strike');for(let i=0;i<9;i++)tickEggScorpion(b,player());assert.equal(scorpionDanger(b,{...player(),x}),true);assert.equal(scorpionDanger(b,{...player(),x:x+90}),false);});
test('only airborne attack during bite recovery damages the eyes once',()=>{const b=createEggScorpion(arena);assert.equal(strike(b),false);until(b,'bite-open');const g=scorpionGeometry(b);assert.equal(damageEggScorpion(b,{...player(),x:g.eyes[0].x,y:g.eyes[0].y}),false);assert.equal(strike(b),true);assert.equal(b.hits,1);assert.equal(strike(b),false);});
test('three distinct bite hits break glasses, open laser tail and destroy armor',()=>{const b=createEggScorpion(arena);for(let i=1;i<=3;i++){until(b,'bite-open');assert.equal(strike(b),true);assert.equal(b.hits,i);if(i===2){assert.equal(b.laserMode,true);until(b,'laser-windup');assert.equal(scorpionDanger(b,player()),false);until(b,'laser-fire');assert.ok(b.beam);} }assert.equal(b.state,'destroyed');assert.equal(b.bites,3);until(b,'defeated');});
test('missed openings repeat indefinitely and allow a later win',()=>{const b=createEggScorpion(arena);for(let i=0;i<5;i++){until(b,'bite-open');tickEggScorpion(b,player());until(b,'idle');}assert.equal(b.hits,0);assert.equal(b.bites,5);for(let i=0;i<3;i++){until(b,'bite-open');assert.equal(strike(b),true);}assert.equal(b.state,'destroyed');});
test('laser collision follows finite segment, not the whole screen',()=>{const b=createEggScorpion(arena);b.hits=2;b.laserMode=true;until(b,'laser-fire');const {a,z}=b.beam,m={x:(a.x+z.x)/2,y:(a.y+z.y)/2};assert.equal(scorpionDanger(b,{...player(),...m}),true);assert.equal(scorpionDanger(b,{...player(),x:m.x,y:m.y-100}),false);});
test('anchored body and pincers remain solid dangerous armor outside exposed eyes',()=>{const b=createEggScorpion(arena);until(b,'idle');const g=scorpionGeometry(b);assert.equal(scorpionDanger(b,{...player(),x:g.body.x,y:b.y-20}),true);assert.equal(scorpionDanger(b,{...player(),x:g.claws[0].x,y:b.y-20}),true);});
test('the first two hits shatter distinct eye panels and damaged glass is not a second weak spot',()=>{const b=createEggScorpion(arena);until(b,'bite-open');assert.equal(strike(b),true);assert.deepEqual(b.shattered,[true,false]);until(b,'bite-open');const broken=scorpionGeometry(b).eyes[0];assert.equal(damageEggScorpion(b,{...player(),...broken,ground:false,jumpAttack:true}),false);const e=scorpionGeometry(b).eyes[1];assert.equal(damageEggScorpion(b,{...player(),...e,ground:false,jumpAttack:true}),true);assert.deepEqual(b.shattered,[true,true]);});
